"""
Fourier-space likelihood functions (isolated from likelihoods.py).

These mirror the time-domain lnL_* functions but evaluate the Gaussian residual in
the (real) Fourier domain, which lets stationary (correlated) stellar variability be
absorbed by a per-frequency noise spectrum instead of being modelled and subtracted
in the time domain. The model light curve is still generated by the existing PyTransit
simulators (imported from likelihoods.py) on the uniform folded `time` grid; only the
residual comparison moves to Fourier space.

Conventions:
  * FFT = the positive-frequency coefficients from np.fft.rfft(x), with the DC
    (k=0) bin DROPPED and, for even-length inputs, the purely real Nyquist bin also
    DROPPED. Every retained coefficient is therefore genuinely complex and follows
    the same density. Dropping DC makes the likelihood insensitive to the overall
    flux offset / mean (the variability baseline).
  * flux_ft  -- these retained rfft coefficients of the folded, dilution-corrected
    data flux, precomputed ONCE per star (model-independent).
  * var_ft   -- per-frequency power (= E[|X_k|^2], the variance of each retained
    complex rfft bin), same length as flux_ft. Built by the caller from the folded
    power spectrum `psd_folded` and the number of un-gapped transits `ntransits` as
        var_ft = psd_folded / ntransits
    so the cost here, sum(|R_k|^2/var_ft), reproduces sum(|R_k|^2/psd) * ntransits.
  * Return value is the complex-Gaussian cost sum(|R_k|^2/var_ft) (positive, NO 1/2:
    for a complex coefficient of power var_ft the Gaussian exponent is -|R_k|^2/var_ft,
    the 1/2 and the two real/imag components cancelling). The calling loglike adds the
    model-independent normalisation -sum(log(pi*var_ft)) and negates.
"""

import numpy as np

from ..likelihoods.real import (
    simulate_TP_transit,
    simulate_EB_transit,
    simulate_EB_transit_secondary,
    simulate_EB_transit_evenodd,
    mean_anomaly_difference,
)

pi = np.pi


def _rfft_complex_bins(x: np.ndarray) -> np.ndarray:
    """Return only complex positive-frequency bins of a real-input DFT.

    DC is always removed. For an even-length input, ``rfft``'s final Nyquist
    coefficient is purely real and has a one-dimensional Gaussian density, so it
    is removed rather than incorrectly scoring it with the complex-normal formula.
    """
    x = np.asarray(x)
    coeff = np.fft.rfft(x)[1:]
    if x.size % 2 == 0:
        coeff = coeff[:-1]
    return coeff


# Backward-compatible internal name used throughout this module.
_rfft_nodc = _rfft_complex_bins


def _fourier_chi2(flux_ft: np.ndarray, model_ft: np.ndarray,
                  var_ft: np.ndarray) -> float:
    """Complex-Gaussian cost sum(|R_k|^2/var_ft) between a data rfft and a model
    rfft at fixed per-bin power var_ft (no 1/2; see module note)."""
    resid = flux_ft - model_ft
    return np.sum((resid.real**2 + resid.imag**2) / var_ft)


def lnL_TP_fourier(time: np.ndarray, flux_ft: np.ndarray, var_ft: np.ndarray,
                   R_p: float, P_orb: float, inc: float, a: float, R_s: float,
                   u1: float, u2: float, ecc: float, argp: float,
                   companion_fluxratio: float = 0.0,
                   companion_is_host: bool = False,
                   exptime: float = 0.00139,
                   nsamples: int = 20):
    """
    Fourier-space analogue of lnL_TP. Returns the complex-Gaussian cost
    sum(|R_k|^2/var_ft) on the DC-dropped rfft of the folded light curve.
    `flux_ft` and `var_ft` are precomputed by the caller (see module note
    above); all other arguments match lnL_TP.
    """
    model = simulate_TP_transit(
        time, R_p, P_orb, inc, a, R_s, u1, u2,
        ecc, argp,
        companion_fluxratio, companion_is_host,
        exptime, nsamples
        )
    return _fourier_chi2(flux_ft, _rfft_nodc(model), var_ft)


def lnL_EB_fourier(time: np.ndarray, flux_ft: np.ndarray, var_ft: np.ndarray,
                   sigma_veto: float,
                   R_EB: float, EB_fluxratio: float, P_orb: float, inc: float,
                   a: float, R_s: float, u1: float, u2: float,
                   ecc: float, argp: float,
                   companion_fluxratio: float = 0.0,
                   companion_is_host: bool = False,
                   exptime: float = 0.00139,
                   nsamples: int = 20):
    """
    Fourier-space analogue of lnL_EB (primary window only). Preserves the
    legacy hard secondary-depth veto: the scenario is rejected (returns +inf,
    i.e. lnL -> -inf) when the predicted secondary depth exceeds 1.5*sigma_veto,
    where sigma_veto is the scalar time-domain flux uncertainty.
    """
    model, secdepth = simulate_EB_transit(
        time, R_EB, EB_fluxratio, P_orb, inc, a, R_s, u1, u2,
        ecc, argp,
        companion_fluxratio, companion_is_host,
        exptime, nsamples
        )
    if secdepth >= 1.5*sigma_veto:
        return np.inf
    return _fourier_chi2(flux_ft, _rfft_nodc(model), var_ft)


def lnL_EB_second_fourier(time: np.ndarray, flux_ft: np.ndarray,
                          var_ft: np.ndarray,
                          time_secondary: np.ndarray, flux_sec_ft: np.ndarray,
                          var_sec_ft: np.ndarray,
                          R_EB: float, EB_fluxratio: float, P_orb: float,
                          inc: float, a: float, R_s: float, u1: float,
                          u2: float, ecc: float, argp: float,
                          companion_fluxratio: float = 0.0,
                          companion_is_host: bool = False,
                          exptime: float = 0.00139,
                          nsamples: int = 20,
                          max_shift: float = None):
    """
    Fourier-space analogue of lnL_EB_second: primary + secondary windows, each
    compared in its own DC-dropped rfft domain. `flux_ft`/`var_ft` describe the
    primary window and `flux_sec_ft`/`var_sec_ft` the secondary window.
    """
    # The primary is fixed at the candidate ephemeris while eccentricity moves
    # the secondary away from phase 0.5 by t0.  Full-period Fourier windows are
    # much wider than the local secondary window used by the time-domain
    # pipeline, so impose the same event-selection prior when requested.
    if max_shift is not None:
        allowed_shift = float(max_shift)
        if not np.isfinite(allowed_shift) or allowed_shift <= 0.0:
            return np.inf
        t0 = (mean_anomaly_difference(ecc, argp*(pi/180.)) - 0.5) * P_orb
        if abs(t0) > allowed_shift:
            return np.inf
    model, secmodel = simulate_EB_transit_secondary(
        time, time_secondary, R_EB, EB_fluxratio, P_orb, inc, a, R_s, u1, u2,
        ecc, argp,
        companion_fluxratio, companion_is_host,
        exptime, nsamples
        )
    return (_fourier_chi2(flux_ft, _rfft_nodc(model), var_ft)
            + _fourier_chi2(flux_sec_ft, _rfft_nodc(secmodel), var_sec_ft))


def lnL_EB_evenodd_fourier(time: np.ndarray, flux_ft: np.ndarray,
                           var_ft: np.ndarray,
                           time_secondary: np.ndarray, flux_sec_ft: np.ndarray,
                           var_sec_ft: np.ndarray,
                           R_EB: float, EB_fluxratio: float, P_orb: float,
                           inc: float, a: float, R_s: float, u1: float,
                           u2: float, ecc: float, argp: float,
                           companion_fluxratio: float = 0.0,
                           companion_is_host: bool = False,
                           exptime: float = 0.00139,
                           nsamples: int = 20,
                           max_shift: float = None):
    """
    Fourier-space analogue of lnL_EB_evenodd. `flux_ft`/`var_ft` is the even
    window and `flux_sec_ft`/`var_sec_ft` the odd window. Marginalises over the
    unknown parity-to-eclipse assignment by taking the better (min chi^2) of the
    two labellings, mirroring the time-domain function.
    """
    # The eccentric solution has anomaly offset t0 and displaces the primary
    # and secondary eclipses by -t0/2 and +t0/2.  On a full-period Fourier grid,
    # using the grid extent alone lets the sampler fit unrelated folded
    # variability.  A caller can impose the event-selection prior
    # |t0| <= max_shift, normally a small multiple of the observed duration.
    t0 = (mean_anomaly_difference(ecc, argp*(pi/180.)) - 0.5) * P_orb
    win_half = max(float(np.max(np.abs(time))),
                   float(np.max(np.abs(time_secondary))))
    if abs(t0) / 2.0 > win_half:
        return np.inf
    if max_shift is not None:
        allowed_shift = float(max_shift)
        if not np.isfinite(allowed_shift) or allowed_shift <= 0.0:
            return np.inf
        if abs(t0) > allowed_shift:
            return np.inf
    model, secmodel = simulate_EB_transit_evenodd(
        time, time_secondary, R_EB, EB_fluxratio, P_orb, inc, a, R_s, u1, u2,
        ecc, argp,
        companion_fluxratio, companion_is_host,
        exptime, nsamples
        )
    model_ft = _rfft_nodc(model)
    secmodel_ft = _rfft_nodc(secmodel)
    return min(
        _fourier_chi2(flux_ft, model_ft, var_ft)
        + _fourier_chi2(flux_sec_ft, secmodel_ft, var_sec_ft),
        _fourier_chi2(flux_ft, secmodel_ft, var_ft)
        + _fourier_chi2(flux_sec_ft, model_ft, var_sec_ft),
        )


def lnL_EB_twin_fourier(time: np.ndarray, flux_ft: np.ndarray,
                        var_ft: np.ndarray,
                        R_EB: float, EB_fluxratio: float, P_orb: float,
                        inc: float, a: float, R_s: float, u1: float, u2: float,
                        ecc: float, argp: float,
                        companion_fluxratio: float = 0.0,
                        companion_is_host: bool = False,
                        exptime: float = 0.00139,
                        nsamples: int = 20):
    """
    Fourier-space analogue of lnL_EB_twin (q >= 0.95 / 2xP twin branch). Like
    lnL_EB_fourier but without the secondary-depth veto, matching the
    time-domain twin which applies none.
    """
    model, secdepth = simulate_EB_transit(
        time, R_EB, EB_fluxratio, P_orb, inc, a, R_s, u1, u2,
        ecc, argp,
        companion_fluxratio, companion_is_host,
        exptime, nsamples
        )
    return _fourier_chi2(flux_ft, _rfft_nodc(model), var_ft)
